### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by PH4NT0MK** [KaloKamo/noahwaseaten.com#13]
- [x] Make sure to sleep 8 hours every day
- [ ] #16
- [x] Think about what to do with `Contacts`
- [ ] `Revamp css`
Rethink what the best structure is, unify different css'
Remove lines of css that does nothing
Add margin and padding in *ONLY ONE* place - easier to keep track of
- [ ] Work on videos
- [ ] Implement `view details` in videos

**Comment by noahwaseaten** [comment]
Task failed

I am having near 5 hours of sleep
